/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "primary": "#006c49",
        "primary-container": "#10b981",
        "on-primary": "#ffffff",
        "on-primary-container": "#00422b",
        "primary-fixed": "#6ffbbe",
        "primary-fixed-dim": "#4edea3",
        "on-primary-fixed": "#002113",
        "on-primary-fixed-variant": "#005236",
        "secondary": "#416900",
        "secondary-container": "#acf847",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#457000",
        "secondary-fixed": "#acf847",
        "secondary-fixed-dim": "#91db2a",
        "on-secondary-fixed": "#102000",
        "on-secondary-fixed-variant": "#304f00",
        "tertiary": "#b4136d",
        "tertiary-container": "#ff72b1",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#740043",
        "tertiary-fixed": "#ffd9e4",
        "tertiary-fixed-dim": "#ffb0cd",
        "on-tertiary-fixed": "#3e0022",
        "on-tertiary-fixed-variant": "#8c0053",
        "background": "#faf9f5",
        "on-background": "#1b1c1a",
        "surface": "#faf9f5",
        "on-surface": "#1b1c1a",
        "surface-bright": "#faf9f5",
        "surface-dim": "#dbdad6",
        "surface-variant": "#e3e2df",
        "on-surface-variant": "#3c4a42",
        "surface-container": "#efeeea",
        "surface-container-low": "#f4f4f0",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e9e8e4",
        "surface-container-highest": "#e3e2df",
        "outline": "#6c7a71",
        "outline-variant": "#bbcabf",
        "inverse-surface": "#2f312e",
        "inverse-on-surface": "#f2f1ed",
        "inverse-primary": "#4edea3",
        "error": "#ba1a1a",
        "on-error": "#ffffff",
        "error-container": "#ffdad6",
        "on-error-container": "#93000a",
      },
      fontFamily: {
        sans: ["'Plus Jakarta Sans'", "sans-serif"],
        body: ["'Plus Jakarta Sans'", "sans-serif"],
        headline: ["'Plus Jakarta Sans'", "sans-serif"],
      },
      spacing: {
        "margin-desktop": "48px",
        "margin-tablet": "24px",
        "margin-mobile": "16px",
        "gutter-desktop": "32px",
        "gutter-tablet": "24px",
        "gutter-mobile": "16px",
        "space-1": "4px",
        "space-2": "8px",
        "space-3": "12px",
        "space-4": "16px",
        "space-6": "24px",
        "space-8": "32px",
        "space-10": "96px",
        "space-12": "48px",
        "space-16": "64px",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        "full": "9999px",
      },
    },
  },
  plugins: [],
};
